### ISSUE TITLE
Allow binding sources and sinks to interfaces.

### ISSUE THREAD

**Issue by saurabh-dua** [Spirent/openperf#176]
Currently, they can only be bound to ports.  This should be a minor plumbing issue..

**Comment by cmyers-spirent** [comment]
Currently only adding support for interface level sinks which has clearly defined use case.

It is not well defined how interface level sources are supposed to behave.
It is pretty straight forward to add interface level sources which behave exactly like
port level sources, meaning they build the whole packet.  But since they behave
exactly like port level sources there is no benefit from doing this either. It is just
extra overhead of added code and possible performance impact of managing
different types of sources.
