### ISSUE TITLE
No pid control in any of the generators

### ISSUE THREAD

**Issue by jhiga** [Spirent/openperf#309]
For example, it's how the CPU load generator knows to back down when other generators are using CPU load.

**Comment by loskutnikov-spirent** [comment]
First need to solve #337, because in current state all threads of all generators binds to the core 0. Thus OS scheduler doesn't work with OpenPerf threads.

**Comment by loskutnikov-spirent** [comment]
I made research to find out way to get CPU time per core for particular thread. Seems there is not possible to get such information. 

But we can get the current core number for the thread. I propose to calculate value of thread core time using current core number. We can get the current core before a load spin and consider spin time as core time of the thread. We can also get the current core after the load spin and divide time between two cores. Although, this value will be rough, it is better than nothing.

**Comment by loskutnikov-spirent** [comment]
The block generator of OpenPerf pretty steady and accurate, because @artem-belov improved the original algorithm during migration. So there is no needed add PID control for the block generator. Addition of the PID control can broke the existing algorithm and decrease stability and accuration.

**Comment by loskutnikov-spirent** [comment]
The CPU generator of the OpenPerf enough steady and accurate now, because algorithm was improved during migration. So there is no needed to add the PID control for the CPU generator. Addition of the PID control can broke the existing algorithm and decrease stability and accuracy.

For taking account of impact another OpenPerf threads to CPU generator, we propose implements another mode for making the overall system load, instead of per core load. Issue #343.
