### ISSUE TITLE
DPDK threads take a full CPU core which affects openperf CPU generator performance

### ISSUE THREAD

**Issue by stasiasu** [Spirent/openperf#339]
Testing on an openperf pod with 4 cores, and drive CPU core at 100% for all 4 cores. Openperf reported CPU result is ['99%', '49%', '49%', '99%'], which add up to 296% CPU performance in total versus expectation is 400%.
We understand that DPDK threads are on core1 and core2, and takes up a full core usage, but we want the openperf CPU performance to match cloudstress agent performance.

**Comment by DerangedMonkeyNinja** [comment]
I think this is a symptom of a larger, consistency issue we have with Openperf.  Currently, there is an explicit, user configurable CPU affinity for the DPDK threads in the packetio module but no configurable affinity for threads from other generators. Additionally, the packetio/DPDK threads default to using all available cores and won't run without 2 cores and 1 physical or virtual port.

To resolve this issue, I suggest two changes:

1) Allow packetio to unload itself gracefully.  That way, when no DPDK ports are present or if DPDK is given an explicit core mask of 0x0, the packetio module will just disable itself instead of panicking.  That will allow the other generators to be used without hogging any cores for packetio/DPDK in situations where they are unused.

I'm currently refactoring packetio, so I'll add this feature.

2) Add core affinity as a standard option for all generator modules.  Have generators use all available cores by default, but allow users to explicitly set a core mask for each generator, if needed. This provides a way for users to partition generator resources in a consistent manner. So, if a user does want to use packetio and other load generators, there is an obvious and explicit way to prevent the generators from interfering with each other.

Who wants to take on suggestion 2?

Let's use the key "modules.[generator].cpu-mask" for configuring each generator's mask.

**Comment by belov3004** [comment]
@DerangedMonkeyNinja I will handle suggestion 2

**Comment by abelov-spirent** [comment]
@DerangedMonkeyNinja I will handle suggestion 2
