### ISSUE TITLE
Generate a combined swagger yaml file in make generate

### ISSUE THREAD

**Issue by clintyoshimura** [Spirent/openperf#469]
We wanted to use go-swagger to generate go client/model files for the OpenPerf API, however it does not like the way the yaml swagger file in openperf/api/schema/v1/openperf.yaml is split into subdirectories and linked with $ref.
I don't believe a combined swagger yaml is generated in the make generate command is it?
If it is not, could we add the command to create this combined swagger yaml file to the make generate? The command line that worked for us was:
deps/swagger-codegen/swagger-codegen generate -l swagger-yaml -i api/schema/v1/openperf.yaml -o ./ -DoutputFile=openperf.yaml

**Comment by DerangedMonkeyNinja** [comment]
Yes, swagger can combine multiple files together. You should do that for your project when you need to generate the spec. Since the OP build doesn't need a single file, I don't see any reason to add the combined file as a target to the Makefile.

**Comment by djoyner** [comment]
In this case the downstream project is using `go-swagger` rather than `swagger-codegen` so we'd prefer not to have to vendor the latter as well as bring in the JRE as a build environment dependency. Since OP has this already in place it seems logical to handle it here. It also makes the YAML easier to consume in the general case.
